/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresatursimo.MVC;

/**
 *
 * @author juans
 */
public class InterfazUsuario extends javax.swing.JFrame {

    /**
     * Creates new form InterfazAdministrador
     */
    public InterfazUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        jPanelLogin = new javax.swing.JPanel();
        jButtonNombreUser = new javax.swing.JButton();
        jTextFieldUsuario = new javax.swing.JTextField();
        jButtonPassword = new javax.swing.JButton();
        jTextFieldPassword = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNombreUser.setText("Usuario");
        jButtonNombreUser.setBorderPainted(false);
        jButtonNombreUser.setContentAreaFilled(false);
        jButtonNombreUser.setFocusPainted(false);
        jButtonNombreUser.setFocusable(false);
        jButtonNombreUser.setRequestFocusEnabled(false);
        jButtonNombreUser.setRolloverEnabled(false);
        jButtonNombreUser.setVerifyInputWhenFocusTarget(false);
        jButtonNombreUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNombreUserActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonNombreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 46, 89, -1));
        jPanelLogin.add(jTextFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 47, 170, -1));

        jButtonPassword.setText("Contraseña");
        jButtonPassword.setBorderPainted(false);
        jButtonPassword.setContentAreaFilled(false);
        jButtonPassword.setFocusPainted(false);
        jButtonPassword.setFocusable(false);
        jButtonPassword.setRequestFocusEnabled(false);
        jButtonPassword.setRolloverEnabled(false);
        jButtonPassword.setVerifyInputWhenFocusTarget(false);
        jButtonPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPasswordActionPerformed(evt);
            }
        });
        jPanelLogin.add(jButtonPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 87, -1, -1));
        jPanelLogin.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 88, 170, -1));

        jButtonLogin.setText("Ingresar");
        jButtonLogin.setFocusable(false);
        jPanelLogin.add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNombreUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNombreUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNombreUserActionPerformed

    private void jButtonPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPasswordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonNombreUser;
    private javax.swing.JButton jButtonPassword;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelPrincipal;
    public javax.swing.JTextField jTextFieldPassword;
    public javax.swing.JTextField jTextFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
