/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package empresatursimo.MVC;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JMenuItem;

/**
 *
 * @author juans
 */
public class VentanaAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form VentanaAdministrador
     */
    public VentanaAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelRegistrarUsuario = new javax.swing.JPanel();
        jButtonNCliente = new javax.swing.JButton();
        jButtonDNI = new javax.swing.JButton();
        jButtonTelefono = new javax.swing.JButton();
        jButtonTipo = new javax.swing.JButton();
        jButtonRiesgo = new javax.swing.JButton();
        jTextNUsuario = new javax.swing.JTextField();
        jTextDNI = new javax.swing.JTextField();
        jTextTelefono = new javax.swing.JTextField();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jComboBoxRiesgo = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonNCliente1 = new javax.swing.JButton();
        jTextFieldPassword = new javax.swing.JTextField();
        jPanelCraerPaquete = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jTextDias = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxTpasaje = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxEscalas = new javax.swing.JComboBox<>();
        jButton6 = new javax.swing.JButton();
        jTextDestino = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jTextOrigenVuelo = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jTextIDVuelo = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxHEstrellas = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        jTextNombreH = new javax.swing.JTextField();
        jButton10 = new javax.swing.JButton();
        jPanel = new javax.swing.JPanel();
        jSeparator5 = new javax.swing.JSeparator();
        jButton16 = new javax.swing.JButton();
        jComboBoxCExcursiones = new javax.swing.JComboBox<>();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jComboBoxNBuses = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jButtonCancelarCancelar = new javax.swing.JButton();
        jButtonGuardarPaquete = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonRegistar = new javax.swing.JButton();
        jButtonCrearPaquete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(780, 400));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelRegistrarUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanelRegistrarUsuario.setMaximumSize(new java.awt.Dimension(390, 250));
        jPanelRegistrarUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonNCliente.setText("Contraseña");
        jButtonNCliente.setBorderPainted(false);
        jButtonNCliente.setContentAreaFilled(false);
        jButtonNCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonNCliente.setDefaultCapable(false);
        jButtonNCliente.setFocusPainted(false);
        jButtonNCliente.setFocusable(false);
        jButtonNCliente.setRequestFocusEnabled(false);
        jButtonNCliente.setRolloverEnabled(false);
        jButtonNCliente.setVerifyInputWhenFocusTarget(false);
        jPanelRegistrarUsuario.add(jButtonNCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 90, -1));

        jButtonDNI.setText("DNI:");
        jButtonDNI.setBorderPainted(false);
        jButtonDNI.setContentAreaFilled(false);
        jButtonDNI.setDefaultCapable(false);
        jButtonDNI.setFocusPainted(false);
        jButtonDNI.setFocusable(false);
        jPanelRegistrarUsuario.add(jButtonDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 51, 79, -1));

        jButtonTelefono.setText("Telefono:");
        jButtonTelefono.setBorderPainted(false);
        jButtonTelefono.setContentAreaFilled(false);
        jButtonTelefono.setDefaultCapable(false);
        jButtonTelefono.setFocusPainted(false);
        jButtonTelefono.setFocusable(false);
        jPanelRegistrarUsuario.add(jButtonTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jButtonTipo.setText("Tipo:");
        jButtonTipo.setBorderPainted(false);
        jButtonTipo.setContentAreaFilled(false);
        jButtonTipo.setFocusPainted(false);
        jButtonTipo.setFocusable(false);
        jButtonTipo.setVerifyInputWhenFocusTarget(false);
        jPanelRegistrarUsuario.add(jButtonTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 79, -1));

        jButtonRiesgo.setText("Riesgo");
        jButtonRiesgo.setBorderPainted(false);
        jButtonRiesgo.setContentAreaFilled(false);
        jButtonRiesgo.setDefaultCapable(false);
        jButtonRiesgo.setFocusPainted(false);
        jButtonRiesgo.setFocusable(false);
        jButtonRiesgo.setVerifyInputWhenFocusTarget(false);
        jPanelRegistrarUsuario.add(jButtonRiesgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 79, -1));

        jTextNUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNUsuarioActionPerformed(evt);
            }
        });
        jPanelRegistrarUsuario.add(jTextNUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 12, 295, -1));
        jPanelRegistrarUsuario.add(jTextDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(95, 52, 295, -1));
        jPanelRegistrarUsuario.add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 295, -1));

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","1", "2", "3", "4" }));
        jPanelRegistrarUsuario.add(jComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, 295, -1));

        jComboBoxRiesgo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","1", "2", "3"}));
        jPanelRegistrarUsuario.add(jComboBoxRiesgo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 295, -1));

        jButtonRegistrar.setText("Registrar");

        jButtonCancelar.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonRegistrar)
                .addGap(13, 13, 13)
                .addComponent(jButtonCancelar)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonRegistrar)
                    .addComponent(jButtonCancelar)))
        );

        jPanelRegistrarUsuario.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, 30));

        jButtonNCliente1.setText("Nombre: ");
        jButtonNCliente1.setBorderPainted(false);
        jButtonNCliente1.setContentAreaFilled(false);
        jButtonNCliente1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonNCliente1.setDefaultCapable(false);
        jButtonNCliente1.setFocusPainted(false);
        jButtonNCliente1.setFocusable(false);
        jButtonNCliente1.setRequestFocusEnabled(false);
        jButtonNCliente1.setRolloverEnabled(false);
        jButtonNCliente1.setVerifyInputWhenFocusTarget(false);
        jPanelRegistrarUsuario.add(jButtonNCliente1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 80, -1));
        jPanelRegistrarUsuario.add(jTextFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 290, -1));

        getContentPane().add(jPanelRegistrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 430, 280));

        jPanelCraerPaquete.setMaximumSize(new java.awt.Dimension(780, 250));
        jPanelCraerPaquete.setMinimumSize(new java.awt.Dimension(780, 250));
        jPanelCraerPaquete.setName(""); // NOI18N
        jPanelCraerPaquete.setPreferredSize(new java.awt.Dimension(780, 250));

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setText("Días");
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        jButton3.setRequestFocusEnabled(false);
        jButton3.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jTextDias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDiasActionPerformed(evt);
            }
        });
        jPanel3.add(jTextDias, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 28, 130, -1));

        jSeparator1.setRequestFocusEnabled(false);
        jSeparator1.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 208, 10));

        jButton5.setText("Hotel");
        jButton5.setBorderPainted(false);
        jButton5.setContentAreaFilled(false);
        jButton5.setFocusPainted(false);
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 208, 13));

        jLabel3.setText("Tipo de Pasaje");
        jLabel3.setFocusable(false);
        jLabel3.setInheritsPopupMenu(false);
        jLabel3.setRequestFocusEnabled(false);
        jLabel3.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jComboBoxTpasaje.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","1","2","3" }));
        jComboBoxTpasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTpasajeActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxTpasaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel4.setText("Escala");
        jLabel4.setFocusable(false);
        jLabel4.setInheritsPopupMenu(false);
        jLabel4.setRequestFocusEnabled(false);
        jLabel4.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, -1, -1));

        jComboBoxEscalas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " ,"0", "1","2","3" }));
        jComboBoxEscalas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEscalasActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxEscalas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jButton6.setText("Destino");
        jButton6.setBorderPainted(false);
        jButton6.setContentAreaFilled(false);
        jButton6.setFocusPainted(false);
        jButton6.setFocusable(false);
        jButton6.setRequestFocusEnabled(false);
        jButton6.setVerifyInputWhenFocusTarget(false);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));
        jPanel3.add(jTextDestino, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 1, 130, -1));

        jButton7.setText("Origen");
        jButton7.setBorderPainted(false);
        jButton7.setContentAreaFilled(false);
        jButton7.setFocusPainted(false);
        jButton7.setFocusable(false);
        jButton7.setRequestFocusEnabled(false);
        jButton7.setVerifyInputWhenFocusTarget(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, -1));
        jPanel3.add(jTextOrigenVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 130, -1));

        jButton8.setText("IdVuelo");
        jButton8.setBorderPainted(false);
        jButton8.setContentAreaFilled(false);
        jButton8.setFocusPainted(false);
        jButton8.setFocusable(false);
        jButton8.setRequestFocusEnabled(false);
        jButton8.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));
        jPanel3.add(jTextIDVuelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 130, -1));

        jButton9.setText("Vuelos");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setFocusPainted(false);
        jButton9.setFocusable(false);
        jButton9.setRequestFocusEnabled(false);
        jButton9.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 208, 13));

        jLabel5.setText("Estrellas");
        jLabel5.setFocusable(false);
        jLabel5.setInheritsPopupMenu(false);
        jLabel5.setRequestFocusEnabled(false);
        jLabel5.setVerifyInputWhenFocusTarget(false);
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, -1));

        jComboBoxHEstrellas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","1","2","3", "4", "5" }));
        jComboBoxHEstrellas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxHEstrellasActionPerformed(evt);
            }
        });
        jPanel3.add(jComboBoxHEstrellas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        jPanel3.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 54, 208, 10));
        jPanel3.add(jTextNombreH, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 130, -1));

        jButton10.setText("Nombre");
        jButton10.setBorderPainted(false);
        jButton10.setContentAreaFilled(false);
        jButton10.setFocusPainted(false);
        jButton10.setFocusable(false);
        jButton10.setRequestFocusEnabled(false);
        jButton10.setVerifyInputWhenFocusTarget(false);
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel.setMaximumSize(new java.awt.Dimension(220, 224));
        jPanel.setMinimumSize(new java.awt.Dimension(220, 224));
        jPanel.setPreferredSize(new java.awt.Dimension(220, 224));
        jPanel.setVerifyInputWhenFocusTarget(false);
        jPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 208, 10));

        jButton16.setText("Trasaldo En Bus");
        jButton16.setBorderPainted(false);
        jButton16.setContentAreaFilled(false);
        jButton16.setFocusPainted(false);
        jPanel.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 208, 13));

        jComboBoxCExcursiones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1","2","3","4","5","6","7","8","9","10","11","12"}));
        jPanel.add(jComboBoxCExcursiones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, -1, -1));

        jButton17.setText("Excursiones");
        jButton17.setBorderPainted(false);
        jButton17.setContentAreaFilled(false);
        jButton17.setFocusPainted(false);
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel.add(jButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 208, 13));

        jButton18.setText("Cantidad de Traslados");
        jButton18.setBorderPainted(false);
        jButton18.setContentAreaFilled(false);
        jButton18.setFocusPainted(false);
        jPanel.add(jButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 140, -1));

        jButton21.setText("Cantidad de Escursiones");
        jButton21.setBorderPainted(false);
        jButton21.setContentAreaFilled(false);
        jButton21.setFocusPainted(false);
        jButton21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton21.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jPanel.add(jButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        jComboBoxNBuses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ","1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        jPanel.add(jComboBoxNBuses, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setMaximumSize(new java.awt.Dimension(220, 224));
        jPanel2.setMinimumSize(new java.awt.Dimension(220, 224));
        jPanel2.setPreferredSize(new java.awt.Dimension(220, 224));
        jPanel2.setVerifyInputWhenFocusTarget(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCancelarCancelar.setText("Cancelar");
        jButtonCancelarCancelar.setFocusable(false);
        jPanel2.add(jButtonCancelarCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jButtonGuardarPaquete.setText("Guardar");
        jButtonGuardarPaquete.setFocusable(false);
        jPanel2.add(jButtonGuardarPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        javax.swing.GroupLayout jPanelCraerPaqueteLayout = new javax.swing.GroupLayout(jPanelCraerPaquete);
        jPanelCraerPaquete.setLayout(jPanelCraerPaqueteLayout);
        jPanelCraerPaqueteLayout.setHorizontalGroup(
            jPanelCraerPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCraerPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelCraerPaqueteLayout.setVerticalGroup(
            jPanelCraerPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCraerPaqueteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCraerPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelCraerPaqueteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanelCraerPaquete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 780, 280));

        jPanel4.setFocusable(false);

        jButtonRegistar.setText("Registar Usuario");
        jButtonRegistar.setDoubleBuffered(true);
        jButtonRegistar.setFocusable(false);

        jButtonCrearPaquete.setText("Crear Paquete");
        jButtonCrearPaquete.setDoubleBuffered(true);
        jButtonCrearPaquete.setFocusable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButtonRegistar)
                .addGap(18, 18, 18)
                .addComponent(jButtonCrearPaquete)
                .addContainerGap(261, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRegistar)
                    .addComponent(jButtonCrearPaquete))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 740, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNUsuarioActionPerformed

    private void jComboBoxTpasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTpasajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTpasajeActionPerformed

    private void jComboBoxEscalasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEscalasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEscalasActionPerformed

    private void jTextDiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDiasActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jComboBoxHEstrellasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxHEstrellasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxHEstrellasActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonCancelar;
    public javax.swing.JButton jButtonCancelarCancelar;
    public javax.swing.JButton jButtonCrearPaquete;
    public javax.swing.JButton jButtonDNI;
    public javax.swing.JButton jButtonGuardarPaquete;
    public javax.swing.JButton jButtonNCliente;
    public javax.swing.JButton jButtonNCliente1;
    public javax.swing.JButton jButtonRegistar;
    private javax.swing.JButton jButtonRegistrar;
    public javax.swing.JButton jButtonRiesgo;
    public javax.swing.JButton jButtonTelefono;
    public javax.swing.JButton jButtonTipo;
    public javax.swing.JComboBox<String> jComboBoxCExcursiones;
    public javax.swing.JComboBox<String> jComboBoxEscalas;
    public javax.swing.JComboBox<String> jComboBoxHEstrellas;
    public javax.swing.JComboBox<String> jComboBoxNBuses;
    public javax.swing.JComboBox<String> jComboBoxRiesgo;
    public javax.swing.JComboBox<String> jComboBoxTipo;
    public javax.swing.JComboBox<String> jComboBoxTpasaje;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanelCraerPaquete;
    public javax.swing.JPanel jPanelRegistrarUsuario;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator5;
    public javax.swing.JTextField jTextDNI;
    public javax.swing.JTextField jTextDestino;
    public javax.swing.JTextField jTextDias;
    public javax.swing.JTextField jTextFieldPassword;
    public javax.swing.JTextField jTextIDVuelo;
    public javax.swing.JTextField jTextNUsuario;
    public javax.swing.JTextField jTextNombreH;
    public javax.swing.JTextField jTextOrigenVuelo;
    public javax.swing.JTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables

    

    
}
